
import "./globals.css";
import ServerHeader from "@/components/ServerHeader";
import 'bootstrap/dist/css/bootstrap.min.css';
import ServerFooter from "@/components/ServerFooter";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <ServerHeader />
        {children}
        <ServerFooter />
      </body>
    </html>
  );
}
